# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 17:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IVV',
            fields=[
                ('ivv_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_id', models.CharField(max_length=10)),
                ('submitter_id', models.CharField(max_length=10)),
                ('project_name', models.CharField(max_length=20)),
                ('program_name', models.CharField(choices=[('MMIS', 'MMIS'), ('E&E', 'E&E'), ('HIT', 'HIT')], max_length=10)),
                ('progress_report_date', models.DateTimeField(default=datetime.date(2017, 6, 12))),
                ('activity_one_consult_date', models.DateTimeField(default=datetime.date(2017, 6, 12))),
                ('target_RFP_release_date', models.DateTimeField(default=datetime.date(2017, 6, 12))),
                ('next_progress_report_date', models.DateTimeField(default=datetime.date(2017, 6, 12))),
                ('target_IVV_on_board_date', models.DateTimeField(default=datetime.date(2017, 6, 12))),
                ('executive_summary', models.TextField(default='None')),
                ('total_budget', models.CharField(blank=True, max_length=10)),
                ('earned_value', models.CharField(blank=True, max_length=10)),
                ('budget_variance', models.CharField(blank=True, max_length=10)),
                ('schedule_variance', models.CharField(blank=True, max_length=10)),
                ('other', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LifeCycle',
            fields=[
                ('lc_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, choices=[('No plans for developement', 'No plans for development'), ('Pre-R1', 'Pre-R1'), ('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3')], max_length=40)),
                ('module_business', models.CharField(choices=[('Business Relationship Management', 'Business Relationship Management'), ('Care Management', 'Care Management'), ('Contractor Management', 'Contractor Management'), ('Eligibility & Enrollment', 'Eligibility & Enrollment'), ('Financial Management', 'Financial Management'), ('Member Management', 'Member Management'), ('Operations Management', 'Operations Management'), ('Performance Management', 'Performance Management'), ('Plan Management', 'Plan Management'), ('Provider Management', 'Provider Management')], max_length=50)),
                ('module_functional', models.CharField(choices=[('Member Eligibility', 'Member Eligibility'), ('Member Enrollment', 'Member Enrollment'), ('FFS Claims and Adjudication', 'FFS Claims and Adjudication'), ('Pharmacy', 'Pharmacy'), ('Third Party Liability', 'Third Party Liability'), ('Care Management', 'Care Management'), ('Program Integrity', 'Program Integrity'), ('Decision Support System', 'Decision Support System'), ('Reference Data Management', 'Reference Data Management'), ('Provider Management', 'Provider Management'), ('Registries', 'Registries')], max_length=50)),
                ('target_approval_date', models.CharField(blank=True, help_text='Enter all dates in format DD-MM-YY', max_length=8)),
                ('target_development_date', models.CharField(blank=True, max_length=8)),
                ('target_R1', models.CharField(blank=True, max_length=8)),
                ('target_R2', models.CharField(blank=True, max_length=8)),
                ('target_go_live', models.CharField(blank=True, max_length=8)),
                ('target_R3', models.CharField(blank=True, max_length=8)),
                ('ivv_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('rec_id', models.AutoField(primary_key=True, serialize=False)),
                ('ivv_id', models.CharField(max_length=10)),
                ('recommendation_number', models.CharField(blank=True, max_length=1)),
                ('recommendation_date', models.DateTimeField(default=datetime.datetime(2017, 6, 12, 17, 36, 17, 787993, tzinfo=utc))),
                ('recommendation', models.TextField(default='None')),
                ('resolved', models.CharField(blank=True, max_length=5)),
                ('comments', models.TextField(default='None')),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('risk_id', models.AutoField(primary_key=True, serialize=False)),
                ('ivv_id', models.CharField(max_length=10)),
                ('risk_ID_number', models.CharField(blank=True, max_length=10)),
                ('title', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(default='None')),
                ('probability', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1)),
                ('impact', models.CharField(blank=True, max_length=10)),
                ('score', models.CharField(blank=True, max_length=1)),
                ('target_resolution_date', models.DateTimeField(default=datetime.date(2017, 6, 12))),
                ('status', models.CharField(blank='True', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(default='None', max_length=100)),
                ('POC_name', models.CharField(default='None', max_length=100)),
                ('POC_email', models.CharField(default='None', max_length=100)),
                ('update_date', models.DateTimeField(default=datetime.date(2017, 6, 12))),
            ],
        ),
        migrations.CreateModel(
            name='Submitter',
            fields=[
                ('submitter_id', models.AutoField(primary_key=True, serialize=False)),
                ('submitter_name', models.CharField(default='None', max_length=100)),
                ('submitter_phone', models.CharField(default='None', max_length=10)),
                ('submitter_title', models.CharField(default='None', max_length=10)),
                ('submitter_email', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Buy milk, wash dog etc', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webform.TodoList'),
        ),
    ]
