# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 17:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.CharField(max_length=10)),
                ('submitter_id', models.CharField(max_length=10)),
                ('lc_id', models.CharField(max_length=10)),
                ('risk_id', models.CharField(max_length=10)),
                ('rec_id', models.CharField(max_length=10)),
                ('ivv_id', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='list',
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommendation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 17, 52, 50, 923633, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='TodoItem',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
