# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 17:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0002_auto_20170612_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entire',
            name='lc_id',
        ),
        migrations.RemoveField(
            model_name='entire',
            name='rec_id',
        ),
        migrations.RemoveField(
            model_name='entire',
            name='risk_id',
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommendation_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 12, 17, 59, 28, 241564, tzinfo=utc)),
        ),
    ]
