# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 19:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0003_auto_20170612_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivv',
            name='activity_one_consult_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ivv',
            name='next_progress_report_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ivv',
            name='progress_report_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ivv',
            name='target_IVV_on_board_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='ivv',
            name='target_RFP_release_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='recommendation_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='risk',
            name='target_resolution_date',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='state',
            name='update_date',
            field=models.DateTimeField(default=datetime.date(2017, 6, 13)),
        ),
    ]
