# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0006_auto_20170614_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifecycle',
            name='target_approval_date',
            field=models.CharField(blank=True, help_text='Enter all dates in format MM-DD-YY', max_length=8),
        ),
        migrations.AlterField(
            model_name='state',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 13, 38, 14, 911900, tzinfo=utc)),
        ),
    ]
