# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0007_auto_20170614_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='entire',
            name='report',
            field=models.FileField(db_index=True, default='hi', upload_to='not_used'),
        ),
        migrations.AlterField(
            model_name='state',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 15, 39, 10, 269358, tzinfo=utc)),
        ),
    ]
