# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0009_auto_20170614_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 15, 46, 48, 153783, tzinfo=utc)),
        ),
    ]
