# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-14 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0013_auto_20170614_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 14, 18, 54, 27, 93580, tzinfo=utc)),
        ),
    ]
