# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 19:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0014_auto_20170614_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('rec_one', models.CharField(max_length=50)),
                ('rec_two', models.CharField(max_length=50)),
                ('rec_three', models.CharField(max_length=50)),
                ('rec_four', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='state',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 19, 24, 28, 11628, tzinfo=utc)),
        ),
    ]
