# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webform', '0015_auto_20170615_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='rec_four',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='rec_three',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='email',
            name='rec_two',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='state',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 15, 20, 0, 28, 829834, tzinfo=utc)),
        ),
    ]
